name-template: 'v$NEXT_PATCH_VERSION 🌈'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
      - 'quickfix'
  - title: '🧰 Maintenance'
    label:
      - 'chore'
      - 'refactor'
change-template: '- $TITLE (#$NUMBER)'
prerelease: true
on:
  push:
    branches:
      - develop
template: |
  ## Changes

  $CHANGES
