name-template: 'v$NEXT_PATCH_VERSION 🌈'
tag-template: '$NEXT_PATCH_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
      - 'quickfix'
  - title: '🧰 Maintenance'
    label:
      - 'chore'
      - 'refactor'
prerelease: true
template: |
  ## What’s Changed

  $CHANGES

  ### Contributors

  $CONTRIBUTORS
