template: |
  ## What’s Changed

  $CHANGES

  ## Contributors

  $CONTRIBUTORS

categories:
  - title: '🚀 Features'
    label:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
