using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DistrictEnergy
{
    class TrnSysType
    {
        // This is the base class for a TRNSYS type.  It defines all the things that are comon to types."""
        public TrnSysType(string unit_name, int type_number, int unit_number, int nParameters, int nInputs, string external_file, string external_file_number)
        {
            Unit_name = unit_name;
            Type_number = type_number;
            Unit_number = unit_number;
            NParameters = nParameters;
            NInputs = nInputs;
            External_file = external_file;
            External_file_number = external_file_number;
        }

        public string Parameter_string { get; private set; }
        public string Inputs_string { get; private set; }
        public string Derivatives_string { get; private set; }
        public string Labels_string { get; private set; }
        public string Heading1_string { get; private set; }
        public string Heading2_string { get; private set; }
        public int Initial_inputs { get; private set; }
        public string Unit_name { get; private set; }
        public int Type_number { get; private set; }
        public int Unit_number { get; private set; }
        public int NParameters { get; private set; }
        public int NInputs { get; private set; }
        public int NDerivatives { get; private set; }
        public string External_file { get; private set; }
        public string External_file_number { get; private set; }

        // the following are set separatly
        //public string parameters_string;
        //public string inputs_string;
        //public string derivatives_string;
        //public string labels_string;
        //public string heading1_string;
        //public string heading2_string;
        //public string initial_inputs;

        protected string WriteParameters()
        {
            return Parameter_string;
        }

        protected string WriteInputs()
        {
            return Inputs_string;
        }

        protected string WriteDerivatives()
        {
            return Derivatives_string;
        }

        protected string WriteType()
        {
            string type_string = "* Model \"" + Unit_name + "\" (Type " + Type_number.ToString() + ")\n*\n\n";
            type_string += "UNIT " + Unit_number.ToString() + " TYPE " + Type_number.ToString() + "\t " + Unit_name.ToString() + "\n";
            if (NParameters > 0)
            {
                type_string += "PARAMETERS " + NParameters.ToString() + "\n";
                type_string += WriteParameters();
            }

            else if (NInputs > 0)
            {
                type_string += "INPUTS " + NInputs.ToString() + "\n";
                type_string += WriteInputs();
                type_string += "*** INITIAL INPUT VALUES\n";
                string input_str = String.Join(" ", Initial_inputs);
                type_string += input_str;
            }

            else if (NDerivatives > 0)
            {
                type_string += "\nDERIVATIVES " + NDerivatives.ToString() + "\n";
                type_string += WriteDerivatives();
                type_string += Heading1_string;
                type_string += Heading2_string;
                type_string += Labels_string + "\n";
            }

            else if (External_file != "")
            {
                type_string += "\n*** External files\nASSIGN \"" + External_file + "\" " + External_file_number + "\n";
                type_string += "\n*------------------------------------------------------------------------------\n";
            }

            return type_string;
        }
    }

    //#########################################################################################################
    //# The following make up other components of a deck file that are not Types.
    //#########################################################################################################
    public class Intro
    {
        public string creator;
        public string creation_date;
        public string modified_date;
        public string description;


        protected string WriteIntro()
        {
            return "VERSION 17\n*******************************************************************************\n*** TRNSYS input file (deck) generated by Trnweb\n*** Creator: " + creator + "\n*** Created: " + creation_date + "\n*** Modified: " + modified_date + "\n*** Description: " + description + "\n***\n*** If you edit this file, use the File/Import TRNSYS Input File function in\n*** TrnsysStudio to update the project.\n***\n*** If you have problems, questions or suggestions please contact your local\n*** TRNSYS distributor or mailto:software@cstb.fr\n***\n*******************************************************************************";

        }
    }

    class ControlCards
    {
        public ControlCards(int start, int stop, int data_step)
        {
            Start = start;
            Stop = stop;
            Data_step = data_step;
        }
        public int Start { get ; set; }
        public int Stop { get; set; }
        public int Data_step { get; set; }

    }
}

